name: QuickShop-Test
on: 
  push:
    branches:
    - master
    - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup Maven
      uses: stCarolas/setup-maven@v1
      with:
        maven-version: 3.6.3
    - name: Build with Maven
      run: mvn clean install
#    - name: Upload artifact
#      uses: actions/upload-artifact@v1.0.0
#      with:
#        name: Mohist-1.12.2--server
#        path: build/distributions 
